### ISSUE TITLE
vue-cli-service build fails

### ISSUE THREAD

**Issue by saddle116** [countercept/snake#13]
I am getting the following error message when installing the production version of snake on a CentOS 7 server:

```shell
> snake-skin@1.1.0 build /home/user/snake/snake-skin
> vue-cli-service build

/home/user/snake/snake-skin/node_modules/open/index.js:16
const wslToWindowsPath = async path => {
                               ^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/user/snake/snake-skin/node_modules/@vue/cli-shared-utils/lib/openBrowser.js:9:14)

npm ERR! Linux 3.10.0-957.27.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "run" "build"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! snake-skin@1.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snake-skin@1.1.0 build script 'vue-cli-service build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the snake-skin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     vue-cli-service build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs snake-skin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls snake-skin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/user/snake/snake-skin/npm-debug.log
mv: cannot stat ‘dist’: No such file or directory

```

**Comment by alexkornitzer** [comment]
Sorry for the late reply, that will be because the version of npm/node is too old, even though the README says 6 or above, I stupid pushed the new UI and did not check the new version requirements. I think 8 or above should be sufficient, I will update the README when I find sometime as that is misleading, if easier you could try the docker version.

**Comment by alexkornitzer** [comment]
Closing as the new UI is now live and hence the above is no longer applicable.
